"""
Knowledge Center page for the Diabetes Risk & Care System.

This module allows users to access general information about diabetes
through static content or AI‑generated summaries. It demonstrates how
the language model can be used to supplement the educational material
within the app.
"""

from __future__ import annotations

import streamlit as st

from app.core.llm import chat


def render() -> None:
    """Render the knowledge center page."""
    st.header("Knowledge Center")
    st.markdown(
        """
        This section provides general information about diabetes, its causes,
        symptoms, and prevention strategies. You can also request a summary
        generated by the AI model.

        **What is diabetes?**

        Diabetes is a chronic health condition that affects how your body turns
        food into energy. It occurs when the pancreas cannot produce enough
        insulin or when the body cannot effectively use the insulin it produces.

        **Types of diabetes:**

        - **Type 1 diabetes**: An autoimmune condition where the pancreas produces
          little to no insulin.
        - **Type 2 diabetes**: Develops over time when the body becomes resistant
          to insulin or the pancreas can't produce enough insulin.
        - **Gestational diabetes**: Occurs during pregnancy and usually resolves
          after childbirth.
        """
    )

    if st.button("Generate AI Summary"):
        with st.spinner("Generating summary..."):
            try:
                summary = chat(
                    prompt=(
                        "Provide a concise overview of diabetes, including its types, "
                        "common symptoms, risk factors, and general prevention tips. "
                        "Use friendly language suitable for a general audience."
                    ),
                    system="You are a patient educator explaining diabetes in simple terms.",
                )
            except Exception as exc:
                summary = (
                    "Unable to generate summary because the OpenAI API key is not configured. "
                    f"Exception: {exc}"
                )
        st.markdown(summary)
