# Example secrets configuration for Streamlit.
#
# Copy this file to `.streamlit/secrets.toml` and replace the placeholder
# value with your actual OpenAI API key. Streamlit will automatically
# load the values from `secrets.toml` and make them available via
# st.secrets.

OPENAI_API_KEY = ""